dataset_name="test_data"
mask_prob=1.0
prop_sliding_window=0.5
masked_lm_prob=0.4
dupe_factor=10
max_predictions_per_seq=20
max_seq_length=50
signature="-mp${mask_prob}-sw${prop_sliding_window}-mlp${masked_lm_prob}-df${dupe_factor}-mppq${max_predictions_per_seq}-msl${max_seq_length}"
CKPT_DIR="C:/Users/harry/Desktop/Hyunmin/2024-2/UROP/BERT4BundleRec/checkpoints"
dim=64
batch_size=256
num_train_steps=800000

CUDA_VISIBLE_DEVICES=1 ./.conda/python.exe -u run.py \
    --train_input_file=./data/${dataset_name}${signature}.train.tfrecord \
    --test_input_file=./data/${dataset_name}${signature}.test.tfrecord \
    --vocab_filename=./data/${dataset_name}${signature}.vocab \
    --user_history_filename=./data/${dataset_name}${signature}.his \
    --checkpointDir=${CKPT_DIR}/${dataset_name} \
    --signature=${signature}-${dim}-dp2 \
    --do_train=True \
    --do_eval=True \
    --bert_config_file=./bert_train/bert_config_${dataset_name}_${dim}.json \
    --batch_size=${batch_size} \
    --max_seq_length=${max_seq_length} \
    --max_predictions_per_seq=${max_predictions_per_seq} \
    --num_train_steps=${num_train_steps} \
    --num_warmup_steps=100 \
    --learning_rate=1e-4